---
- name: Promote host to Domain Controller
  ansible.windows.win_domain_controller:
    dns_domain_name: '{{ domain_name }}'
    safe_mode_password: '{{ domain_password }}'
    domain_admin_user: '{{ domain_admin_user }}'
    domain_admin_password: '{{ domain_admin_password }}'
    install_dns: true
    state: domain_controller
  register: domain_controller

- name: Add ActiveDirectory PowerShell module
  community.windows.win_psmodule:
    name: ActiveDirectory
    state: present
  when: domain_controller.changed

- name: Reboot
  ansible.windows.win_reboot:
  when: domain_controller.changed

- name: Add new DC as DNS server in DHCP
  ansible.windows.win_shell: |
    $DNSServers = (Get-DhcpServerv4OptionValue -ScopeId {{ dhcp_scope_id }} -OptionId 6).Value
    if ($DNSServers -NotContains "{{ dc_ip }}") {
      $DNSServers += "{{ dc_ip }}"
      Set-DhcpServerv4OptionValue -ScopeId {{ dhcp_scope_id }} -DnsServer $DNSServers -Force
    }
  delegate_to: '{{ domain_pdc }}'
  when: domain_controller.changed
